baseurl: /Talking_Show
exclude: ['README.md']
title: "The Talking Show"
description: "Nicolas G Miller and Steve Kado present art talking on KCHUNG Radio"
email: steve@d-s.today
url: https://ssssssssk.github.io/Talking_Show
lang: English
permalink: /:year/:month/:title/

prose:
  rooturl: '_posts'
  
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "episodes"
      - name: "number"
        field: 
          element: number
          label: "episode number"
          
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""