baseurl: /Talking_Show
exclude: ['README.md']
title: "The Talking Show"
description: "Nicolas G Miller and Steve Kado present art talking on KCHUNG Radio"
email: steve@d-s.today
url: http://thetalkingshow.org
lang: English
permalink: /:year/:month/:title/

prose:
  rooturl: '_posts'
  
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "episodes"
      - name: "number"
        field: 
          element: "number"
          label: "episode number"
      - name: "title"
        field: 
          element: "text"
          label: "Episode Title"
      - name: "date"
        field: 
          element: "text"
          label: "YYYY-MM-DD"
      - name: "meta"
        field:
          element: "text"
          label: "link to audio file"
      - name: "excerpt"
        field:
          element: "text"
          label: "Short Blurb"
      - name: "duration"
        field:
          element: "text"
          label: "duration as MM:SS"
      - name: "category"
        field:
          element: "hidden"
          value: "episodes"


