baseurl: /Talking_Show
exclude: ['README.md']
title: The-Talking-Show
description: "Nicolas G Miller and Steve Kado present art talking on KCHUNG Radio"
email: steve@d-s.today
url: https://ssssssssk.github.io/Talking_Show/
lang: English
permalink: /:day/:month/:year/:title/
